# Generated by Django 3.2 on 2024-04-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('format', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metacritic_critic_score', models.IntegerField()),
                ('metacritic_reviews', models.IntegerField()),
                ('metacritic_user_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('metacritic_user_reviews', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.album')),
            ],
        ),
        migrations.CreateModel(
            name='Aoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoty_critic_score', models.IntegerField()),
                ('aoty_critic_reviews', models.IntegerField()),
                ('aoty_user_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('aoty_user_reviews', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoty_reviews', to='accounts.album')),
            ],
        ),
    ]
